language: ruby
cache: bundler
script: 'bundle exec rake'
sudo: required
dist: trusty
rvm:
  - 2.5.1

before_install:
  - gem update bundler
  - sudo apt-get update
  - wget --no-check-certificate http://www.freedesktop.org/software/harfbuzz/release/harfbuzz-1.8.3.tar.bz2 && tar -xjf harfbuzz-1.8.3.tar.bz2 --no-same-owner
  - cd harfbuzz-1.8.3 && sudo ./configure && sudo make && sudo make install && rm -rf harfbuzz*

notifications:
  email:
    recipients:
      - tomas.celizna@gmail.com
    on_failure: change
    on_success: never
