language: ruby
cache: bundler
script: 'bundle exec rake'
sudo: required
dist: trusty
rvm:
  - 2.5.1

before_install:
  - gem update bundler
  - sudo apt-get update
  - sudo apt-get install -y libharfbuzz-dev

notifications:
  email:
    recipients:
      - tomas.celizna@gmail.com
    on_failure: change
    on_success: never
